---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tailscale
  namespace: flux-system
spec:
  interval: 1h
  url: https://pkgs.tailscale.com/helmcharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: flux-system
spec:
  targetNamespace: tailscale
  interval: 1h
  chart:
    spec:
      chart: tailscale-operator
      sourceRef:
        kind: HelmRepository
        name: tailscale
      interval: 1h
  valuesFrom:
    - kind: Secret
      name: tailscale-auth
      valuesKey: client_id
      targetPath: oauth.clientId
    - kind: Secret
      name: tailscale-auth
      valuesKey: client_secret
      targetPath: oauth.clientSecret
  values:
    # To expose a service, annotate it with:
    #   tailscale.com/expose: "true"
